// The pool of quotes RaceRoom picks from (see RaceRoom.pickQuote()). Rewritten
// from real, wildly varied social-media posts and threads (found via
// compilation articles, since Reddit/X/Threads themselves are unreachable
// from here, see ARCHITECTURE.md's Status log) plus originals written to
// match that same variety, rather than one uniform voice. Every entry had its
// specifics changed and any names/handles stripped, so nothing here is a
// verbatim repost. Kept in its own file since RaceRoom.ts shouldn't have to
// scroll past 200 strings to get to the actual room logic.
export const QUOTES = [
  // Rewritten from real posts: absurdist one-offs and overheard moments
  "So today I was looking at a girl because she had lettuce in her hair, and she just said, I have a boyfriend.",
  "I tried rolling a joint for the first time and somehow rolled my own ankle instead.",
  "My fingerprint scanner refuses to recognize me unless there's a faint layer of chicken tender grease on my thumb.",
  "Unplug the router for one single second and the whole household reacts like the building is on fire.",
  "There's a very specific fatherly urge to just abandon everyone and walk into the woods for a while.",
  "New strategy: tell every date I know a spot, then drive them straight to a therapist's office.",
  "My ten year old niece just casually announced that horseradish, if it were alive, would probably be non-binary.",
  "I will stop that microwave at exactly one second left, nobody has time for the whole countdown.",
  "The clarity that hits you right after a 2am fast food run is a uniquely brutal kind of self awareness.",
  "Ten p.m. at your parents' house as an adult somehow feels exactly like 3am used to feel in your own apartment.",
  "Every morning my toddler bolts upright in bed and screams HELP, I WOKE UP, like it's a genuine crisis.",
  "Seeing a close friend's handwriting for the first time feels weirdly personal, like why is it so bad.",
  "Someone asked if anyone in the room was named Jeff, and a guy named Geoff answered anyway, just to be difficult.",
  "My partner told me to release the spider outside instead of killing it, so we took it out and got drinks after.",
  "Not to sound like a walking self help poster, but sunlight and fresh air genuinely change your whole mood.",
  "The meeting started with my boss asking, completely serious, if you were me, would you fire you.",
  "My younger brother thinks it's hilarious to call me old, so I think it's hilarious to leave him waiting.",
  "You want me to get a partner? The exact kind of person who ruins every true crime documentary?",
  "A CEO once found an employee digging through the trash for food and called it inspiring instead of alarming.",
  "That kid in the holiday movie could have just called the police at literally any point in the story.",
  "If you're cremated, you could technically end up inside an hourglass and still get to join board game night.",
  "Somebody pointed out that the new graduate with a math degree doesn't just understand sin, he understands cosine too.",
  "Having a father is somehow its own entire personality trait, apparently.",
  "Grandma, can you come get me from my rap battle? It's over. No, I lost, just come get me, please.",
  "A guy at the dog park told his dog no, and then quietly added, we talked about this.",
  "The single most cutting thing you can say about someone is just, who's this clown.",
  "A sci-fi writer built an entire fictional doomsday machine as a warning, and people built the real one anyway.",
  "Between food, internet, rent, and an oddly specific candle habit, the monthly budget stopped making sense.",

  // Rewritten: wholesome real moments
  "My son finished dead last in the race because he ran straight past the finish line to hug me instead. Worth it.",
  "An elderly man was seen quietly dropping off a bag of tennis balls at the animal shelter, no announcement, just kindness.",
  "Overheard two kids arguing about love: do you think you'll ever fall for someone. Only if she likes pancakes, honestly.",
  "A substitute school photographer got to take the yearbook photo of the class service dog and cried a little, understandably.",
  "Someone's neighbor spent an hour in the snow pushing strangers' cars free without ever being asked.",
  "A regular at the diner started quietly covering the bill for anyone eating alone on their birthday.",
  "A kid at the bus stop offered his umbrella to a stranger and then just walked home in the rain, no big deal to him.",
  "Someone found their dog's old collar years later and just sat on the floor holding it for a while.",

  // Rewritten: chaotic/unhinged real posts
  "New plan: adopt a parrot and only ever teach it four phrases, all of them deeply unsettling out of context.",
  "On a first date, asked what I do for work, I panicked and said something vague about selling questionable snacks.",
  "I got an entry level job at the cable company purely so I could fix my own internet without ever calling support.",
  "I have to work hard because, unfortunately, nobody's exactly lining up to buy pictures of my feet.",
  "I hate going out in public, mainly because the public insists on also being there.",
  "There's a very specific anxiety in ignoring three thousand five star reviews to fixate on the two one star ones.",
  "Someone tried to make a drink flavored like a childhood snack cake, and the internet had a lot of feelings about it.",
  "It's strange that movies kept trying to top one iconic villain with scarier villains instead of just funnier ones.",
  "Venting, as far as I can tell, mostly involves saying I don't know in six increasingly dramatic tones of voice.",
  "You genuinely cannot land a spaceship on a planet made entirely of gas, no matter how badly the game wants you to try.",
  "Getting an advanced degree mainly so I can say ah, just what the doctor ordered, unironically, for the rest of my life.",
  "I'm training a new intern and today's big unprompted idea was, quote, have we tried just making more money.",
  "I love that bands still pretend to leave the stage before the encore, like theatrical peekaboo for adults.",
  "Dating an older man is not always what it's cracked up to be, especially when he starts quoting old proverbs mid-argument.",
  "My mom silently brings cut fruit into my room without a word, and that's when it hits me nobody will ever love me quite like that again.",
  "The music played for adults in stores growing up was deeply uncool, and now apparently it's full of certified bangers from my own youth.",
  "My partner built a fire in the backyard, put their hands on their hips, stared at it for five minutes, and declared cavemen must have been thrilled.",

  // Rewritten: relatable everyday observations
  "That little handle above a car door exists purely so a nervous passenger has something dramatic to grab onto.",
  "A customer service chat rep casually mentioned mid-conversation that he forgot his wife's birthday, and things escalated fast.",
  "A brand new intern's entire first pitch to the whole team was simply, have we considered making more revenue.",
  "Somebody's toddler had a full meltdown today, and the official household explanation was just, full moon, it happens.",
  "I'm saving a certain slow burn crime drama to watch together, since apparently that's a real relationship milestone now.",
  "Forget the ex talk, I want to know which friend you promised to marry if you're both still single at thirty.",
  "There's a specific joy in learning someone your exact age is already divorced, like congratulations, you lapped the field.",
  "My partner asked for another slice of toast, clearly expecting a second dirty knife, but I'd already planned ahead perfectly.",
  "Marriage is mostly just texting back and forth asking if you need anything from the store, forever, until one of you stops.",
  "My partner hid an online story from over a thousand people today just so they could post a picture of me instead.",
  "My partner and I have a nightly game where we each try to sneak off and brush our teeth without the other one noticing.",
  "We hired a college intern, and on day one he sent a message asking, sorry if this was already brought up, but have we tried increasing revenue.",

  // Short deadpan one-liners
  "Autocorrect has ended more friendships than actual arguments ever will.",
  "Nobody has ever successfully eaten just one chip straight from the bag.",
  "The remote always goes missing right as the show gets interesting.",
  "Every group chat has exactly one person who only ever replies in emojis.",
  "Somehow every charger cable ends up exactly one inch too short.",
  "The printer only jams the day you're already running late.",
  "Every playlist has one song you skip without fail, every single time.",
  "The smoke alarm only ever goes off when you're cooking something simple.",
  "Every family gathering somehow circles back to someone's diet.",
  "The other lane always looks faster no matter which one you actually pick.",
  "Every online quiz insists you're either a genius or a golden retriever.",
  "Small talk about the weather has kept civilization running for centuries.",
  "The last five percent of a phone battery lasts exactly four seconds.",
  "Every parking lot becomes a maze right when you need to leave in a hurry.",
  "There's always one wobbly table leg no folded napkin can truly fix.",
  "Every calendar reminder feels like a personal attack the moment it fires.",
  "Nobody warns you that adulthood is mostly just deciding what's for dinner.",
  "The gym is suspiciously empty every January after the first two weeks.",
  "Every group photo has one person blinking at exactly the wrong second.",
  "Nobody has ever regretted a nap, but plenty regret skipping one.",
  "The fastest way to boil a watched pot is to just walk away from it.",
  "Every household has one drawer full of cables nobody can identify.",
  "The best ideas always arrive right as you're trying to fall asleep.",
  "Somehow the one day you skip checking the weather is the day it pours.",
  "The instructions always say keep the box, right before you toss it.",
  "Nobody's phone autocorrect has ever once picked the word they meant.",
  "Every escalator moves at a speed that's technically walking but feels rude.",
  "The bag of ice always seems heavier than the actual groceries somehow.",
  "There's always exactly one sock that never makes it back from the wash.",
  "The good parking spot only opens up right after you've given up looking.",

  // Longer rambling run-ons
  "I hate when my touch ID refuses to recognize me first thing in the morning, like come on, you already know it's me, we do this every single day, nothing has changed.",
  "There's a special kind of silence that only exists in the exact seconds after you've sent an accidentally awkward text and watched the delivered label appear underneath it.",
  "Somehow every group project throughout all of school and beyond has one person who contributes nothing until the literal hour before the deadline, and yet still takes credit.",
  "The absolute chaos of trying to find a show to watch together, scrolling for forty minutes, agreeing on nothing, and eventually just rewatching something you've both already seen twice.",
  "Every single time a meeting could have been an email, someone still schedules thirty minutes, mutes their mic, and stares blankly at a spreadsheet nobody asked to see.",
  "The specific dread of hearing your name called out in a waiting room after you've already mentally rehearsed exactly what you're going to say and somehow still blank on all of it.",
  "There is nothing quite like opening the fridge for the fourth time in ten minutes, fully expecting new options to have appeared since the last three times you checked.",
  "Every road trip eventually reaches that exact moment where nobody wants to be the one to suggest a bathroom stop, so everyone just quietly suffers in quiet solidarity instead.",
  "The universal experience of typing a whole paragraph explaining yourself, rereading it, deleting it entirely, and just sending ok instead because it felt like too much effort.",
  "Somehow every attempt to fold a fitted sheet ends the exact same way, in a lumpy ball shoved into the back of the closet, regardless of how many tutorials you've watched.",
  "There's a very specific frustration in finally getting comfortable in bed only to remember you forgot to turn off a light, lock a door, or check something completely trivial.",
  "The way an entire room goes quiet the second you whisper something to one specific person, as if everyone else has suddenly developed incredible hearing on command.",
  "Every group vacation eventually produces one person who insists on documenting absolutely everything while somehow never actually appearing in a single one of the photos.",
  "There's a unique kind of panic in realizing halfway through a haircut that you can no longer politely stop the process, so you just accept whatever happens next.",
  "The specific chaos of a group chat during a live sports event, where forty messages appear in ten seconds and half of them are just variations of screaming.",
  "Somehow every time you finally decide to clean out one drawer, you end up sitting on the floor for an hour reading old birthday cards instead of actually cleaning anything.",
  "There's a very particular anxiety in hearing footsteps behind you at night and speeding up slightly, only to realize it's someone equally anxious walking at your exact same pace.",
  "Every attempt to take a professional headshot ends with roughly two hundred photos, one usable one, and a newfound understanding of why celebrities hire actual photographers.",
  "The distinct horror of realizing mid-sentence in a meeting that you've been confidently mispronouncing a common word for your entire adult life, apparently.",
  "There's a very specific kind of tired that only comes from a day where absolutely nothing happened, and yet somehow every single task still felt exhausting to complete.",
  "Every attempt to assemble furniture ends with at least one mystery screw left over, a vague sense of unease, and a promise to yourself to check the instructions eventually.",
  "The chaos of trying to merge two playlists for a road trip, where compromise is impossible and everyone quietly resents everyone else's taste in music the entire drive.",
  "There's a strange comfort in rewatching a show you've already seen a dozen times, because somehow knowing exactly what happens next is more relaxing than any surprise could be.",
  "Every attempt to take a candid photo ends up looking staged, and every attempt to pose naturally ends up looking like a missing person's poster, there's no in between.",
  "The specific dread of a shared document where you can see someone else typing in real time and have absolutely no idea what they're about to say or delete.",
  "There's a very real skill in nodding along to a story you've already heard twice before, reacting with genuine surprise at the exact same twist for a third time.",
  "Every group hangout eventually reaches the moment where everyone stands near the door for twenty more minutes, having a whole second conversation before actually leaving.",
  "The universal experience of confidently walking into a room, immediately forgetting why, and then just standing there hoping the reason reveals itself eventually.",
  "There's a specific kind of guilt in leaving a voicemail, knowing the person will just read the transcript instead, and the transcript will make no sense whatsoever.",
  "Every attempt to explain a dream out loud reveals halfway through that it made a lot more sense as a feeling than as an actual sequence of describable events.",

  // Trivia, varied openers
  "Octopuses have three hearts, and two of them stop beating entirely whenever the octopus swims.",
  "A single cloud can weigh over a million pounds while still floating comfortably above your head.",
  "Bananas contain enough potassium to register as faintly, harmlessly radioactive on a sensitive enough detector.",
  "The Eiffel Tower actually grows a few inches taller in summer as its iron expands in the heat.",
  "Sharks predate trees, meaning they were swimming around long before forests existed anywhere on land.",
  "A group of flamingos is officially called a flamboyance, which feels like an unusually accurate choice.",
  "Wombats produce cube shaped droppings, a shape that stops them from rolling away downhill.",
  "There are more possible unique chess games than there are atoms in the entire observable universe.",
  "Some turtle species can absorb oxygen through openings near their tail while fully underwater.",
  "Butterflies taste using sensors in their feet rather than anything resembling a tongue.",
  "A day on Venus technically lasts longer than an entire year spent orbiting around the sun.",
  "Sea otters often hold hands while sleeping so ocean currents don't drift them apart overnight.",
  "Cows form real friendships with specific herd members and show measurable stress when separated from them.",
  "A single bolt of lightning burns roughly five times hotter than the surface of the sun itself.",
  "Polar bears actually have black skin hidden beneath their thick layer of translucent white fur.",
  "Nearly all the gold ever mined throughout human history would only fill about three olympic swimming pools.",
  "The human nose is estimated to be capable of distinguishing over a trillion individual scents.",
  "Koalas have fingerprints so close to human ones that they've reportedly confused crime scene evidence before.",
  "It technically rains diamonds deep within the atmospheres of both Jupiter and Saturn, according to researchers.",
  "An ostrich's eyeball is physically larger than its entire brain.",
  "Grasshoppers have their hearing organs located on their abdomen instead of anywhere near their head.",
  "A crocodile physically cannot stick out its tongue, since it's anchored to the roof of its own mouth.",
  "The combined weight of all ants alive on Earth roughly rivals the combined weight of all humans.",
  "A group of crows is called a murder, while a group of owls is called a parliament.",
  "Honey found sealed in ancient Egyptian tombs has been tested and found still perfectly edible.",
  "Scotland's official national animal is the unicorn, chosen centuries ago as a symbol of purity.",
  "The shortest recorded war in history reportedly lasted under forty minutes before ending in surrender.",
  "Some species of jellyfish are biologically capable of reverting back to an earlier stage of life indefinitely.",
  "A single teaspoon of a neutron star would weigh roughly as much as a mountain here on Earth.",
  "The inventor of the modern frisbee was, after his death, cremated and turned into actual frisbees.",

  // Wholesome/relatable anecdotes
  "A stranger at the grocery store quietly paid for someone's groceries after their card got declined, no name given, no fuss made.",
  "Someone's grandfather still writes the exact same joke inside every birthday card, and everyone still laughs anyway.",
  "A kid at recess gave up his turn on the swing so the new student wouldn't have to stand there alone.",
  "Someone found their childhood dog's tag in a drawer years later and just held it for a minute before putting it back.",
  "A bus driver waited an extra thirty seconds every single morning for the same student who was always almost late.",
  "Someone's coworker quietly covers for them every year on the anniversary of a hard day, no questions asked.",
  "A stranger returned a lost wallet with all the cash still inside and just said, hope your day gets better.",
  "Someone's neighbor mows the whole block's lawns every summer and refuses to ever explain why.",
  "A kid saved up an entire summer of allowance just to buy his mom a coffee maker for her birthday.",
  "Someone's old teacher still remembers their name, decades later, the second they run into each other at the store.",
  "A stranger held an elevator for a full minute for someone visibly struggling with too many grocery bags.",
  "Someone's dad still checks the weather in a city they haven't lived in for twenty years, just in case.",
  "A group of strangers spent an entire afternoon helping a family push a stalled car off a busy road.",
  "Someone's roommate leaves the porch light on every single night, just in case anyone comes home late.",
  "A kid at the pool taught a much younger stranger how to swim, entirely unprompted, over one single afternoon.",
  "Someone's grandmother still keeps a jar of coins specifically for parking meters, just in case anyone needs one.",
  "A stranger noticed someone crying in their car and just left a coffee on the windshield without saying a word.",
  "Someone's old coach still shows up to every single game, even for players who graduated years ago.",
  "A kid gave his umbrella to a stranger at the bus stop and just walked the rest of the way home in the rain.",
  "Someone's neighbor shovels the entire street every winter before anyone else has even woken up.",
  "A stranger let a nervous new driver merge in front of them with a genuinely encouraging wave, not an annoyed one.",
  "Someone's older sibling still calls every single week, no matter how far apart they end up living.",
  "A librarian quietly waived a decade old late fee and just said, welcome back, we missed you.",
  "Someone's dad taught every kid on the street to ride a bike, one summer at a time, for years.",
  "A stranger noticed someone counting change at the register and quietly covered the rest without a word.",

  // Rhetorical hot takes and questions
  "Cereal is technically a soup if you think about the definition for slightly too long.",
  "A hot dog is basically a sandwich, no matter how loudly people insist otherwise.",
  "Pineapple on pizza is fine, and this debate has gone on far longer than it ever should have.",
  "Most remakes are unnecessary, the originals usually aged perfectly fine without any help.",
  "Reply-all emails should legally require a short cooling off period before they're allowed to send.",
  "Waiting rooms exist purely to test exactly how patient humanity has actually become.",
  "Silent mode should be the default setting on every single phone the moment it's manufactured.",
  "Board games reveal more about someone's real personality than any job interview ever could.",
  "A long walk solves more actual problems than people ever seem to give it credit for.",
  "Handwritten notes still mean more than any text message ever really manages to.",
  "The best vacations somehow always involve doing almost nothing productive at all.",
  "Rewatching a favorite show is its own quietly underrated form of self care.",
  "Escalators moving slightly faster would probably fix half of rush hour's actual problems.",
  "Most self help advice quietly boils down to sleep more and put the phone down occasionally.",
  "Group chats peak in the first week and slowly fade into background noise after that.",
  "Why does every charging cable in existence somehow end up exactly one inch too short.",
  "Why do escalators always break down into stairs instead of just being stairs from the start.",
  "Is a folded slice of pizza actually a taco now, or does that logic just fall apart immediately.",
  "Why does the group chat go silent for weeks and then suddenly produce two hundred messages overnight.",
  "Why do instructions always say keep this box for storage, directly before you throw the box away.",
];
