// The pool of quotes RaceRoom picks from (see RaceRoom.pickQuote()). Original
// sentences written in the spirit of popular AskReddit-style threads (life
// advice, trivia, humor, relationship/work takes) rather than copied or
// paraphrased from any specific comment, so there's nothing here to attribute
// or infringe. Kept in its own file since RaceRoom.ts shouldn't have to scroll
// past 200 strings to get to the actual room logic.
export const QUOTES = [
  // Life advice / wisdom
  "Comparison is the thief of joy, so stop measuring your life against someone else's highlight reel.",
  "The people who mind don't matter, and the people who matter don't mind.",
  "You can't pour from an empty cup, so take care of yourself first.",
  "Nobody is thinking about you as much as you think they are.",
  "Most of what you worry about today will be forgotten in a week.",
  "Being kind costs nothing but means everything to the person on the other end.",
  "The best time to start was yesterday, the next best time is right now.",
  "You are not required to set yourself on fire to keep other people warm.",
  "Half the arguments you have could be avoided if you asked one clarifying question first.",
  "Nobody remembers your mistakes as vividly as you do, so let yourself move on.",
  "The quickest way to feel better about your life is to stop scrolling through everyone else's.",
  "It's okay to outgrow friendships, not every relationship is meant to last forever.",
  "Rest is not something you earn, it's something you actually need.",
  "The version of you from five years ago would be amazed at how far you've come.",
  "Saying no to the wrong things is how you say yes to the right ones.",
  "Most people are too busy worrying about themselves to judge you as harshly as you think.",
  "A bad day is not the same thing as a bad life, keep some perspective.",
  "The things you're avoiding are usually the things you most need to do.",
  "You don't need permission to change your mind about something.",
  "Growth feels uncomfortable because you're becoming someone you haven't met yet.",
  "Nobody is coming to save you, so you might as well start saving yourself.",
  "The story you tell yourself about your past can change without changing the facts.",
  "Being wrong quickly is better than being wrong for a long time out of stubbornness.",
  "Most regrets come from things left unsaid, not things that were said too soon.",
  "Your twenties are for making mistakes, not for having it all figured out.",
  "The people who truly love you want you to rest as much as they want you to succeed.",
  "A closed mouth doesn't get fed, so ask for what you actually need.",
  "Time doesn't heal everything, but it does make most things easier to carry.",
  "You can love someone and still choose not to keep them in your life.",
  "The advice you keep avoiding is usually the advice you need the most.",

  // Funny observations
  "Autocorrect has ended more friendships than actual arguments ever will.",
  "The gym is suspiciously empty every single January after the first two weeks.",
  "Nothing ruins a productive morning faster than checking your phone for one second.",
  "Every group chat has exactly one person who only responds with emojis.",
  "The remote control always goes missing right when the show gets interesting.",
  "Nobody has ever successfully eaten just one chip from the bag.",
  "Every parking lot becomes a maze the moment you actually need to leave quickly.",
  "The last five percent of a phone battery seems to last exactly four seconds.",
  "Somehow the printer only jams when you're already running late.",
  "Every household has one drawer that's just full of unidentifiable cables.",
  "Small talk about the weather has kept human civilization running for centuries.",
  "The moment you sit down with food, someone always needs something from you.",
  "Every playlist has one song you skip every single time without fail.",
  "Nobody warns you that adulthood is mostly deciding what to make for dinner.",
  "The instructions always say to keep the box, right before you throw it away.",
  "There is a special kind of silence that only happens after you send an awkward text.",
  "Every calendar reminder feels like a personal attack the moment it actually goes off.",
  "The other lane always seems to be moving faster no matter which one you pick.",
  "Somehow every charger cable ends up exactly one inch too short.",
  "Every group project has one person who somehow disappears until the deadline.",
  "The smoke alarm only ever goes off when you're cooking something simple.",
  "Nobody has ever regretted taking a nap, but plenty regret skipping one.",
  "Every online quiz insists you're either a genius or a golden retriever.",
  "The best ideas always show up right as you're trying to fall asleep.",
  "Every family gathering somehow ends up being about someone's diet.",
  "There's always one wobbly table leg that no amount of napkins can fully fix.",
  "Every voicemail from an unknown number turns out to be about your car's warranty.",
  "Somehow the one day you don't check the weather is the day it rains.",
  "Every group photo has someone blinking at exactly the wrong moment.",
  "The fastest way to make a watched pot boil is to walk away and forget about it.",

  // Interesting facts / trivia
  "Honey never spoils, archaeologists have found pots of it thousands of years old still edible.",
  "Octopuses have three hearts and blue blood running through all of them.",
  "A single cloud can weigh over a million pounds while still floating above you.",
  "Bananas are naturally slightly radioactive because of their potassium content.",
  "The Eiffel Tower grows taller in summer as the metal expands from the heat.",
  "Sharks have been around longer than trees, existing since before forests did.",
  "A group of flamingos is called a flamboyance, which feels perfectly accurate.",
  "Wombat droppings are cube shaped, which keeps them from rolling away.",
  "There are more possible chess games than atoms in the observable universe.",
  "Some turtles can breathe through openings near their tail while underwater.",
  "The shortest war in history lasted under an hour before ending in surrender.",
  "Butterflies taste with their feet instead of using anything like a tongue.",
  "A day on Venus is longer than its entire year spent orbiting the sun.",
  "Sea otters hold hands while sleeping so they don't drift apart in the water.",
  "The inventor of the frisbee was turned into a frisbee himself after he passed.",
  "Cows have best friends and get visibly stressed when separated from them.",
  "Scotland's national animal is the unicorn, chosen for its symbolism of purity.",
  "A bolt of lightning is roughly five times hotter than the surface of the sun.",
  "Polar bears have black skin hidden underneath their thick white fur.",
  "Almost all the world's gold ever mined would only fill about three swimming pools.",
  "Some cats are actually allergic to humans due to proteins found in our skin.",
  "The human nose is capable of detecting over a trillion distinct scents.",
  "Venus is the hottest planet in the solar system, not the one closest to the sun.",
  "Koalas have fingerprints so similar to human ones they can confuse a crime scene.",
  "The longest recorded flight of a chicken lasted only about thirteen seconds.",
  "It technically rains diamonds on both Jupiter and Saturn, according to scientists.",
  "An ostrich's eye is bigger than its entire brain, oddly enough.",
  "Grasshoppers have ears located on their bellies rather than on their heads.",
  "A crocodile cannot stick its tongue out, since it's fixed to the roof of its mouth.",
  "The total weight of ants on Earth roughly rivals the total weight of humans.",

  // Relationships
  "The right person makes distance feel small and effort feel completely worth it.",
  "A good relationship is two people choosing each other again every single day.",
  "Communication problems are rarely about the words, they're about the timing.",
  "The strongest couples argue about the dishes and still go to bed holding hands.",
  "You can miss someone and still know that letting them go was the right choice.",
  "Trust is built in small moments, not in one grand dramatic gesture.",
  "The best partners make ordinary days feel like they're worth remembering.",
  "Love isn't about finding someone perfect, it's about choosing someone consistently.",
  "A relationship built on convenience rarely survives the first real challenge.",
  "Real friends tell you the truth even when a lie would be easier to hear.",
  "The way someone treats a waiter says more than any first date conversation.",
  "You can love your family and still need some distance from them sometimes.",
  "Some friendships fade not because of a fight, but simply because life moved on.",
  "A partner who listens without trying to fix everything is rarer than you think.",
  "The right relationship doesn't require you to shrink yourself to fit into it.",
  "Long distance works when both people treat the relationship like a priority.",
  "The healthiest couples still have separate hobbies and separate friends.",
  "Forgiveness doesn't mean forgetting, it means choosing peace over resentment.",
  "A single honest conversation can save months of quiet resentment later.",
  "The people worth keeping are the ones who show up during the hard seasons.",

  // Work / career
  "A job that pays well but drains you completely is still a bad trade overall.",
  "The best resume in the world can't fix a genuinely toxic work environment.",
  "Burnout doesn't announce itself, it just quietly drains you until you notice.",
  "Nobody on their deathbed wishes they had spent more time answering emails.",
  "A good manager makes your job easier, a bad one makes it your whole personality.",
  "The interview process rarely tells you what the job is actually going to feel like.",
  "Taking a vacation day is not the same thing as taking a mental health day.",
  "The most valuable skill at work is knowing when to actually ask for help.",
  "A raise that comes with double the workload isn't really a raise at all.",
  "Meetings that could have been an email are a small tragedy of modern work.",
  "The best career advice is to negotiate, most people never even try.",
  "Loyalty to a company rarely gets returned the way loyalty to people does.",
  "Working hard and working smart are not always the same strategy.",
  "The job title matters less than whether you actually enjoy the daily work.",
  "A single toxic coworker can make an otherwise great job feel unbearable.",
  "Nobody gets remembered for the hours they worked, only for what they built.",
  "Quiet quitting is just a new name for finally enforcing your own boundaries.",
  "The best time to start job hunting is while you still have a job at all.",
  "A good work culture shows up in small moments, not in the mission statement.",
  "Your job should fund your life, not become the entirety of it.",

  // Motivational / mindset
  "Discipline is choosing between what you want now and what you want most.",
  "Consistency beats intensity, small daily effort adds up faster than bursts of it.",
  "Confidence is built through small proofs that you can handle hard things.",
  "You don't need to feel motivated to start, you just need to start anyway.",
  "Every expert was once a beginner who simply refused to quit early.",
  "Progress hides in boring repetition long before it shows up as a breakthrough.",
  "The goal isn't to never fail, it's to fail fast and adjust quickly.",
  "Momentum is easier to keep going than it is to start from nothing.",
  "You are allowed to be both a work in progress and completely worthy right now.",
  "Comparison kills momentum faster than any actual failure ever could.",
  "Small consistent habits quietly outperform occasional bursts of ambition.",
  "The hardest part of any goal is usually just showing up on the bad days.",
  "Nobody becomes confident by waiting, confidence comes from taking the first step.",
  "Your future self is built entirely from the choices your present self makes today.",
  "Discipline feels heavy at first and weightless once it becomes a habit.",
  "Doubt kills more dreams than actual failure ever manages to.",
  "The best motivation is proof, so give yourself small wins to point back to.",
  "You don't have to see the whole staircase to decide to take the first step.",
  "Effort compounds quietly until one day it's suddenly very visible.",
  "Rest when you need to, but never quit on a day you feel your weakest.",

  // Weird true stories
  "A man once mailed himself across the country in a wooden crate to save on train fare.",
  "A vending machine has technically killed more people than sharks do most years.",
  "A library book was once returned a hundred years late along with an apology note.",
  "A town in Wales adopted one of the longest place names in the world to attract tourists.",
  "A pilot once landed a plane safely after losing an entire section of its roof midair.",
  "A man survived being struck by lightning seven separate times in his life.",
  "A goat was once elected honorary mayor of a small town in the United States.",
  "A painting once sold for millions despite being explicitly labeled unfinished.",
  "A prisoner once escaped a facility by mailing himself out of it inside a box.",
  "A city in Japan holds an annual festival built entirely around crying babies.",
  "A man legally changed his name to a word that was invented to mean nothing at all.",
  "An entire village in Italy was once auctioned off online for one dollar.",
  "A pizza delivery once took over sixty years to arrive due to a lost order.",
  "A single duel in history was fought entirely using cannons instead of pistols.",
  "A man once tried to sell the Eiffel Tower to unsuspecting scrap metal buyers.",
  "A whole country once switched calendars overnight and skipped eleven days.",
  "A basketball game once had a final score so lopsided the losing team asked to stop.",
  "An entire island disappeared from maps after cartographers realized it never existed.",
  "A man was once legally declared dead by mistake and had to fight in court to prove otherwise.",
  "A shipment of lost sea cargo once washed ashore fully intact after decades adrift.",

  // Things people wish they knew earlier
  "Nobody actually has it all figured out, they're just better at hiding the confusion.",
  "Most adults are quietly guessing their way through decisions just like you are.",
  "It's completely fine to change career paths more than once in your life.",
  "Nobody is grading your twenties, despite how it might feel from the inside.",
  "The friends worth keeping don't need constant maintenance to stay close.",
  "It's okay to not enjoy something everyone else seems to love.",
  "Financial literacy should be taught far earlier than it usually is.",
  "Most fears shrink dramatically the moment you actually name them out loud.",
  "You're allowed to leave a situation the moment it stops serving you.",
  "Nobody else is keeping score of your mistakes the way you think they are.",
  "It's fine to outgrow hobbies you once thought defined your whole personality.",
  "Asking for help early is almost always easier than fixing a bigger mess later.",
  "Most decisions are reversible, so the fear of choosing wrong is usually overblown.",
  "You don't have to justify resting to anyone, including yourself.",
  "The people who matter most rarely need grand gestures to feel appreciated.",

  // Unpopular opinions / hot takes
  "Cereal is technically a soup if you really think about the definition too hard.",
  "A hot dog is basically a sandwich no matter how loudly people argue otherwise.",
  "Pineapple on pizza is fine, and the debate has gone on far longer than it should.",
  "Most remakes are unnecessary, the originals usually aged perfectly fine.",
  "Reply-all emails should require a cooling off period before they get sent.",
  "Group chats peak in the first week and slowly become background noise after that.",
  "Waiting rooms exist purely to test how patient humanity has actually become.",
  "Escalators moving slightly faster would probably fix half of rush hour's problems.",
  "Most self help advice boils down to sleep more and stop doom scrolling.",
  "Silent mode should be the default setting on every phone ever manufactured.",
  "Board games reveal more about someone's personality than any interview could.",
  "A long walk solves more problems than people give it credit for.",
  "Handwritten notes mean more than any text message ever could.",
  "The best vacations involve doing almost nothing productive at all.",
  "Rewatching a favorite show is its own underrated form of self care.",
];
